services:
  redis_fsm:
    image: redis:7-alpine
    container_name: fsm_redis
    ports:
      - "6379:6379"

  router_api:
    build: .
    container_name: router_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis_fsm
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    command: >
      bash -c "python -m src.train_and_export && 
               uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - redis_fsm

  router_ui:
    build: .
    container_name: router_streamlit
    ports:
      - "7501:8501"
    environment:
      - API_URL=http://router_api:8000
    volumes:
      - ./frontend:/app/frontend
      - ./src:/app/src
    command: streamlit run frontend/app.py --server.address 0.0.0.0
    depends_on:
      - router_api
